"use client";
import {Canvas,useFrame,useThree} from "@react-three/fiber";
import {useRef,useState,type RefObject} from "react";
import * as THREE from "three";
type Props={onPositionChange?:(x:number,z:number)=>void;onNearbyChange?:(name:string|null)=>void;move?:{x:number;z:number};cameraInput?:{x:number;y:number};cameraActive?:boolean;};
const places=[["CBD Office",-8,-9,7,6,6],["Wuse Shop",8,-10,6,5,6],["Garki Shop",-9,9,6,4.4,6],["Jabi Apartment",9,10,7,6,5],["Street Kiosk",-13,-1,4,3.4,5]] as const;
function Player({move,playerRef,onPositionChange}:{move?:Props["move"];playerRef:RefObject<THREE.Group|null>;onPositionChange?:Props["onPositionChange"]}){const g=useRef<THREE.Group>(null),la=useRef<THREE.Group>(null),ra=useRef<THREE.Group>(null),ll=useRef<THREE.Group>(null),rl=useRef<THREE.Group>(null),t=useRef(0);useFrame((_,d)=>{const p=g.current;if(!p)return;playerRef.current=p;const v=new THREE.Vector2(move?.x??0,move?.z??0),moving=v.lengthSq()>.01;if(moving){v.normalize();const n=p.position.clone();n.x=THREE.MathUtils.clamp(n.x+v.x*8*d,-34,34);n.z=THREE.MathUtils.clamp(n.z+v.y*8*d,-34,34);p.position.copy(n);p.rotation.y=Math.atan2(v.x,v.y);onPositionChange?.(n.x,n.z);t.current+=d*12}const s=moving?Math.sin(t.current)*.6:0;if(la.current)la.current.rotation.x=s;if(ra.current)ra.current.rotation.x=-s;if(ll.current)ll.current.rotation.x=-s;if(rl.current)rl.current.rotation.x=s});return <group ref={g} position={[0,.05,6]}><mesh castShadow position={[0,1.72,0]}><sphereGeometry args={[.34,20,16]}/><meshStandardMaterial color="#7b4b32"/></mesh><mesh castShadow position={[0,1.95,0]}><sphereGeometry args={[.36,20,16]}/><meshStandardMaterial color="#17130f"/></mesh><mesh castShadow position={[0,1.08,0]}><boxGeometry args={[.68,.82,.4]}/><meshStandardMaterial color="#17834b"/></mesh><group ref={la} position={[-.43,1.28,0]}><mesh position={[0,-.35,0]}><capsuleGeometry args={[.12,.48,6,10]}/><meshStandardMaterial color="#7b4b32"/></mesh></group><group ref={ra} position={[.43,1.28,0]}><mesh position={[0,-.35,0]}><capsuleGeometry args={[.12,.48,6,10]}/><meshStandardMaterial color="#7b4b32"/></mesh></group><group ref={ll} position={[-.19,.62,0]}><mesh position={[0,-.42,0]}><capsuleGeometry args={[.14,.62,6,10]}/><meshStandardMaterial color="#222b3a"/></mesh></group><group ref={rl} position={[.19,.62,0]}><mesh position={[0,-.42,0]}><capsuleGeometry args={[.14,.62,6,10]}/><meshStandardMaterial color="#222b3a"/></mesh></group></group>}
function Building({a}:{a:typeof places[number]}){const[,x,z,w,h,d]=a;return <group position={[x,h/2,z]}><mesh castShadow receiveShadow><boxGeometry args={[w,h,d]}/><meshStandardMaterial color="#9a8f80"/></mesh><mesh position={[0,-h/2+1,d/2+.03]}><boxGeometry args={[1.2,1.4,.08]}/><meshStandardMaterial color="#4c2c1e"/></mesh><mesh position={[0,0,d/2+.04]}><boxGeometry args={[2,.9,.06]}/><meshStandardMaterial color="#4e9bc7"/></mesh></group>}
function Scene({move,onPositionChange,onNearbyChange,cameraInput,cameraActive}:{move?:Props["move"];onPositionChange?:Props["onPositionChange"];onNearbyChange?:Props["onNearbyChange"];cameraInput?:Props["cameraInput"];cameraActive?:boolean}){const pr=useRef<THREE.Group|null>(null);const {camera}=useThree();const yaw=useRef(0),pitch=useRef(.48),lastCamera=useRef({x:0,y:0}),last=useRef<string|null>(null);useFrame((_,d)=>{const p=pr.current;if(!p)return;if(cameraActive){const dx=(cameraInput?.x??0)-lastCamera.current.x,dy=(cameraInput?.y??0)-lastCamera.current.y;yaw.current-=dx*.012;pitch.current=THREE.MathUtils.clamp(pitch.current-dy*.009,.18,1.15);lastCamera.current={x:cameraInput?.x??0,y:cameraInput?.y??0}}else{lastCamera.current={x:cameraInput?.x??0,y:cameraInput?.y??0}}const dist=10;const off=new THREE.Vector3(Math.sin(yaw.current)*dist,3.8+pitch.current*4,Math.cos(yaw.current)*dist);const desired=p.position.clone().add(off);camera.position.lerp(desired,1-Math.pow(.0005,d));camera.lookAt(p.position.x,1.05,p.position.z);let hit:string|null=null,best=99;for(const a of places){const[name,x,z,w,,dd]=a;const q=Math.hypot(p.position.x-x,p.position.z-z),r=Math.max(w,dd)*.75+2.2;if(q<r&&q<best){hit=name;best=q}}if(hit!==last.current){last.current=hit;onNearbyChange?.(hit)}});return <><ambientLight intensity={1.3}/><directionalLight position={[8,14,6]} intensity={2.4} castShadow/><mesh rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[80,80]}/><meshStandardMaterial color="#68705f"/></mesh><mesh position={[0,.02,0]}><boxGeometry args={[8,.04,80]}/><meshStandardMaterial color="#252825"/></mesh><mesh position={[0,.03,0]}><boxGeometry args={[80,.04,8]}/><meshStandardMaterial color="#252825"/></mesh>{places.map(a=><Building key={a[0]} a={a}/>)}<Player move={move} onPositionChange={onPositionChange} playerRef={pr}/></>}
export default function AbujaWorld(p:Props){return <div className="world-canvas"><Canvas shadows camera={{position:[0,7,15],fov:55}}><Scene {...p}/></Canvas></div>}